package pub_test

import (
	"testing"
	"testing/fstest"

	"github.com/Alge/tillit/ecosystems/internal/testutil"
	"github.com/Alge/tillit/ecosystems/pub"
)

type pubPackage struct {
	ID, Version string
}

func parsePub(t *testing.T, content string) (pkgs []pubPackage, warnings []string) {
	t.Helper()
	fsys := fstest.MapFS{
		"pubspec.lock": &fstest.MapFile{Data: []byte(content)},
	}
	res, err := (pub.PubspecLock{}).Parse(fsys, "pubspec.lock")
	if err != nil {
		t.Fatalf("Parse failed: %v", err)
	}
	for _, p := range res.Packages {
		if p.Ecosystem != "pub" {
			t.Errorf("Ecosystem = %q, want pub", p.Ecosystem)
		}
		pkgs = append(pkgs, pubPackage{p.PackageID, p.Version})
	}
	return pkgs, res.Warnings
}

func TestPubspecLock_Identity(t *testing.T) {
	a := pub.PubspecLock{}
	if a.Ecosystem() != "pub" {
		t.Errorf("Ecosystem() = %q, want pub", a.Ecosystem())
	}
	if a.Name() != "pubspec.lock" {
		t.Errorf("Name() = %q, want pubspec.lock", a.Name())
	}
	cases := []struct {
		path string
		want bool
	}{
		{"pubspec.lock", true},
		{"./pubspec.lock", true},
		{"/some/path/pubspec.lock", true},
		{"pubspec.yaml", false},
		{"go.sum", false},
		{"pubspec.lock.bak", false},
		{"", false},
	}
	for _, tc := range cases {
		if got := a.CanParse(tc.path); got != tc.want {
			t.Errorf("CanParse(%q) = %v, want %v", tc.path, got, tc.want)
		}
	}
}

func TestPubspecLock_Parse_HostedPackages(t *testing.T) {
	pkgs, warnings := parsePub(t, `# Generated by pub
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      sha256: "deadbeef"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "cafef00d"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
`)
	if len(pkgs) != 2 {
		t.Fatalf("expected 2 packages, got %d: %+v", len(pkgs), pkgs)
	}
	got := map[string]string{}
	for _, p := range pkgs {
		got[p.ID] = p.Version
	}
	if got["http"] != "1.1.0" || got["meta"] != "1.10.0" {
		t.Errorf("unexpected: %+v", got)
	}
	if len(warnings) != 0 {
		t.Errorf("expected no warnings, got: %v", warnings)
	}
}

func TestPubspecLock_Parse_SkipsGitSource(t *testing.T) {
	pkgs, warnings := parsePub(t, `packages:
  ok:
    dependency: "direct main"
    description: {name: ok, sha256: "abc", url: "https://pub.dev"}
    source: hosted
    version: "1.0.0"
  from_git:
    dependency: "direct main"
    description:
      path: "."
      ref: HEAD
      resolved-ref: "abc123"
      url: "https://github.com/foo/bar.git"
    source: git
    version: "0.1.0"
`)
	if len(pkgs) != 1 || pkgs[0].ID != "ok" {
		t.Errorf("expected only hosted pkg, got: %+v", pkgs)
	}
	if !testutil.WarningContains(warnings, "from_git") {
		t.Errorf("expected warning, got: %v", warnings)
	}
}

func TestPubspecLock_Parse_SkipsPathAndSdk(t *testing.T) {
	pkgs, warnings := parsePub(t, `packages:
  myapp:
    dependency: "direct main"
    description: {path: "..", relative: true}
    source: path
    version: "0.1.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
`)
	if len(pkgs) != 0 {
		t.Errorf("expected no packages, got: %+v", pkgs)
	}
	if len(warnings) < 2 {
		t.Errorf("expected two warnings (path + sdk), got: %v", warnings)
	}
}

func TestPubspecLock_Parse_DedupsRepeatEntries(t *testing.T) {
	// Hard to actually emit duplicates from real pub.lock (YAML map
	// keys must be unique), but the parser shouldn't crash if it
	// somehow encounters the same (name, version) again.
	pkgs, _ := parsePub(t, `packages:
  http:
    dependency: "direct main"
    description: {name: http, sha256: "abc", url: "https://pub.dev"}
    source: hosted
    version: "1.0.0"
`)
	if len(pkgs) != 1 {
		t.Errorf("expected 1 package, got: %+v", pkgs)
	}
}

func TestPubspecLock_Parse_MissingFileErrors(t *testing.T) {
	_, err := (pub.PubspecLock{}).Parse(fstest.MapFS{}, "pubspec.lock")
	if err == nil {
		t.Error("expected error when file missing")
	}
}

func TestPubspecLock_Parse_MalformedYAMLErrors(t *testing.T) {
	fsys := fstest.MapFS{
		"pubspec.lock": &fstest.MapFile{Data: []byte("packages:\n  http: [this is not how this works:")},
	}
	_, err := (pub.PubspecLock{}).Parse(fsys, "pubspec.lock")
	if err == nil {
		t.Error("expected error on malformed YAML")
	}
}

func TestPubspecLock_Parse_EmptyLockfile(t *testing.T) {
	pkgs, _ := parsePub(t, `packages: {}`)
	if len(pkgs) != 0 {
		t.Errorf("expected no packages, got: %+v", pkgs)
	}
}
