package cargo_test

import (
	"strings"
	"testing"
	"testing/fstest"

	"github.com/Alge/tillit/ecosystems/cargo"
	"github.com/Alge/tillit/ecosystems/internal/testutil"
)

type cargoPackage struct {
	ID, Version string
}

func parseCargo(t *testing.T, content string) (pkgs []cargoPackage, warnings []string) {
	t.Helper()
	fsys := fstest.MapFS{
		"Cargo.lock": &fstest.MapFile{Data: []byte(content)},
	}
	res, err := (cargo.CargoLock{}).Parse(fsys, "Cargo.lock")
	if err != nil {
		t.Fatalf("Parse failed: %v", err)
	}
	for _, p := range res.Packages {
		if p.Ecosystem != "cargo" {
			t.Errorf("Ecosystem = %q, want cargo", p.Ecosystem)
		}
		pkgs = append(pkgs, cargoPackage{p.PackageID, p.Version})
	}
	return pkgs, res.Warnings
}

func TestCargoLock_Identity(t *testing.T) {
	a := cargo.CargoLock{}
	if a.Ecosystem() != "cargo" {
		t.Errorf("Ecosystem() = %q, want cargo", a.Ecosystem())
	}
	if a.Name() != "Cargo.lock" {
		t.Errorf("Name() = %q, want Cargo.lock", a.Name())
	}
	cases := []struct {
		path string
		want bool
	}{
		{"Cargo.lock", true},
		{"./Cargo.lock", true},
		{"/some/path/Cargo.lock", true},
		{"Cargo.toml", false},
		{"go.sum", false},
		{"Cargo.lock.bak", false},
		{"cargo.lock", false}, // case-sensitive — Rust uses uppercase C
		{"", false},
	}
	for _, tc := range cases {
		if got := a.CanParse(tc.path); got != tc.want {
			t.Errorf("CanParse(%q) = %v, want %v", tc.path, got, tc.want)
		}
	}
}

func TestCargoLock_Parse_RegistryPackages(t *testing.T) {
	pkgs, warnings := parseCargo(t, `
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "anyhow"
version = "1.0.75"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a4668cab20f66d8d020e1fbc0ebe47217433c1b6c8f2040faf858554e394ace6"

[[package]]
name = "serde"
version = "1.0.190"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"
`)
	if len(pkgs) != 2 {
		t.Fatalf("expected 2 packages, got %d: %+v", len(pkgs), pkgs)
	}
	got := map[string]string{}
	for _, p := range pkgs {
		got[p.ID] = p.Version
	}
	if got["anyhow"] != "1.0.75" || got["serde"] != "1.0.190" {
		t.Errorf("unexpected: %+v", got)
	}
	if len(warnings) != 0 {
		t.Errorf("expected no warnings, got: %v", warnings)
	}
}

func TestCargoLock_Parse_SkipsGitSource(t *testing.T) {
	pkgs, warnings := parseCargo(t, `
[[package]]
name = "ok"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"

[[package]]
name = "from-git"
version = "0.1.0"
source = "git+https://github.com/foo/bar.git#abc123def"
`)
	if len(pkgs) != 1 || pkgs[0].ID != "ok" {
		t.Errorf("expected only registry pkg, got: %+v", pkgs)
	}
	if !testutil.WarningContains(warnings, "from-git") {
		t.Errorf("expected warning, got: %v", warnings)
	}
}

func TestCargoLock_Parse_SkipsWorkspaceMember(t *testing.T) {
	// No source field = workspace member / local crate. Skip without
	// a noisy warning since this is the normal case for the project's
	// own crates.
	pkgs, warnings := parseCargo(t, `
[[package]]
name = "myapp"
version = "0.1.0"

[[package]]
name = "anyhow"
version = "1.0.75"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"
`)
	if len(pkgs) != 1 || pkgs[0].ID != "anyhow" {
		t.Errorf("expected only the registry pkg, got: %+v", pkgs)
	}
	// Workspace skip should not produce a warning — these are
	// expected and noisy if surfaced for every project.
	for _, w := range warnings {
		if strings.Contains(w, "myapp") {
			t.Errorf("did not expect workspace-member warning, got: %v", warnings)
		}
	}
}

func TestCargoLock_Parse_SkipsPathSource(t *testing.T) {
	pkgs, warnings := parseCargo(t, `
[[package]]
name = "from-path"
version = "0.1.0"
source = "path+file:///home/me/local"
`)
	if len(pkgs) != 0 {
		t.Errorf("expected no packages, got: %+v", pkgs)
	}
	if !testutil.WarningContains(warnings, "from-path") {
		t.Errorf("expected warning, got: %v", warnings)
	}
}

func TestCargoLock_Parse_AlternativeRegistryStillVetable(t *testing.T) {
	// Some companies host private cargo registries. The `registry+`
	// prefix marks them as registry-sourced — they should still be
	// vetable through whatever URL TILLIT_CARGO_URL points at.
	pkgs, _ := parseCargo(t, `
[[package]]
name = "internal"
version = "1.0.0"
source = "registry+https://internal.example.com/crates"
checksum = "abc"
`)
	if len(pkgs) != 1 || pkgs[0].ID != "internal" {
		t.Errorf("expected the alternative-registry pkg, got: %+v", pkgs)
	}
}

func TestCargoLock_Parse_DedupsRepeatEntries(t *testing.T) {
	// Cargo only emits one entry per (name, version), but the parser
	// should be defensive against duplicates anyway.
	pkgs, _ := parseCargo(t, `
[[package]]
name = "anyhow"
version = "1.0.75"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"

[[package]]
name = "anyhow"
version = "1.0.75"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"
`)
	if len(pkgs) != 1 {
		t.Errorf("expected dedup, got: %+v", pkgs)
	}
}

func TestCargoLock_Parse_KeepsDifferentVersions(t *testing.T) {
	// Two transitively-required versions of the same crate are valid
	// and both should appear in the output (this is the whole point
	// of recording them in the lockfile).
	pkgs, _ := parseCargo(t, `
[[package]]
name = "syn"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "def"
`)
	if len(pkgs) != 2 {
		t.Errorf("expected 2 packages, got: %+v", pkgs)
	}
}

func TestCargoLock_Parse_MissingFileErrors(t *testing.T) {
	_, err := (cargo.CargoLock{}).Parse(fstest.MapFS{}, "Cargo.lock")
	if err == nil {
		t.Error("expected error when file missing")
	}
}

func TestCargoLock_Parse_MalformedTOMLErrors(t *testing.T) {
	fsys := fstest.MapFS{
		"Cargo.lock": &fstest.MapFile{Data: []byte("this is not [[ valid toml")},
	}
	_, err := (cargo.CargoLock{}).Parse(fsys, "Cargo.lock")
	if err == nil {
		t.Error("expected error on malformed TOML")
	}
}

func TestCargoLock_Parse_EmptyLockfile(t *testing.T) {
	pkgs, _ := parseCargo(t, `version = 3`)
	if len(pkgs) != 0 {
		t.Errorf("expected no packages, got: %+v", pkgs)
	}
}
