package hexpm_test

import (
	"strings"
	"testing"
	"testing/fstest"

	"github.com/Alge/tillit/ecosystems/hexpm"
)

type gleamPackage struct {
	ID, Version, Hash string
}

func parseGleam(t *testing.T, content string) (pkgs []gleamPackage, warnings []string) {
	t.Helper()
	fsys := fstest.MapFS{
		"manifest.toml": &fstest.MapFile{Data: []byte(content)},
	}
	res, err := (hexpm.GleamManifest{}).Parse(fsys, "manifest.toml")
	if err != nil {
		t.Fatalf("Parse failed: %v", err)
	}
	for _, p := range res.Packages {
		if p.Ecosystem != "hexpm" {
			t.Errorf("Ecosystem = %q, want hexpm", p.Ecosystem)
		}
		pkgs = append(pkgs, gleamPackage{p.PackageID, p.Version, p.Hash})
	}
	return pkgs, res.Warnings
}

func gleamWarningContains(warns []string, sub string) bool {
	for _, w := range warns {
		if strings.Contains(w, sub) {
			return true
		}
	}
	return false
}

func TestGleamManifest_Identity(t *testing.T) {
	a := hexpm.GleamManifest{}
	if a.Ecosystem() != "hexpm" {
		t.Errorf("Ecosystem() = %q, want hexpm", a.Ecosystem())
	}
	if a.Name() != "manifest.toml" {
		t.Errorf("Name() = %q, want manifest.toml", a.Name())
	}
	cases := []struct {
		path string
		want bool
	}{
		{"manifest.toml", true},
		{"./manifest.toml", true},
		{"/some/path/manifest.toml", true},
		{"gleam.toml", false},    // project file, not lockfile
		{"mix.lock", false},      // sibling adapter's territory
		{"Manifest.toml", false}, // case-sensitive (gleam emits lowercase)
		{"manifest.toml.bak", false},
		{"", false},
	}
	for _, tc := range cases {
		if got := a.CanParse(tc.path); got != tc.want {
			t.Errorf("CanParse(%q) = %v, want %v", tc.path, got, tc.want)
		}
	}
}

func TestGleamManifest_Parse_HexPackages(t *testing.T) {
	pkgs, warnings := parseGleam(t, `# This file was generated by Gleam
# You typically do not need to edit this file

packages = [
  { name = "gleam_stdlib", version = "0.32.0", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "ABC123" },
  { name = "argv", version = "1.0.0", build_tools = ["gleam"], requirements = [], otp_app = "argv", source = "hex", outer_checksum = "DEADBEEF" },
]

[requirements]
gleam_stdlib = { version = "~> 0.32" }
argv = { version = "~> 1.0" }
`)
	if len(pkgs) != 2 {
		t.Fatalf("expected 2 packages, got %d: %+v", len(pkgs), pkgs)
	}
	got := map[string]gleamPackage{}
	for _, p := range pkgs {
		got[p.ID] = p
	}
	if got["gleam_stdlib"].Version != "0.32.0" || got["gleam_stdlib"].Hash != "ABC123" {
		t.Errorf("gleam_stdlib: %+v", got["gleam_stdlib"])
	}
	if got["argv"].Version != "1.0.0" || got["argv"].Hash != "DEADBEEF" {
		t.Errorf("argv: %+v", got["argv"])
	}
	if len(warnings) != 0 {
		t.Errorf("expected no warnings, got: %v", warnings)
	}
}

func TestGleamManifest_Parse_SkipsGitSource(t *testing.T) {
	pkgs, warnings := parseGleam(t, `packages = [
  { name = "ok", version = "1.0.0", source = "hex", outer_checksum = "abc" },
  { name = "from_git", version = "0.1.0", source = "git", repo = "https://github.com/foo/bar" },
]
`)
	if len(pkgs) != 1 || pkgs[0].ID != "ok" {
		t.Errorf("expected only the hex pkg, got: %+v", pkgs)
	}
	if !gleamWarningContains(warnings, "from_git") {
		t.Errorf("expected git warning, got: %v", warnings)
	}
}

func TestGleamManifest_Parse_SkipsLocalSource(t *testing.T) {
	_, warnings := parseGleam(t, `packages = [
  { name = "from_local", version = "0.1.0", source = "local", path = "../local_lib" },
]
`)
	if !gleamWarningContains(warnings, "from_local") {
		t.Errorf("expected local warning, got: %v", warnings)
	}
}

func TestGleamManifest_Parse_DedupsRepeatEntries(t *testing.T) {
	pkgs, _ := parseGleam(t, `packages = [
  { name = "pkg", version = "1.0.0", source = "hex", outer_checksum = "abc" },
  { name = "pkg", version = "1.0.0", source = "hex", outer_checksum = "abc" },
]
`)
	if len(pkgs) != 1 {
		t.Errorf("expected dedup, got: %+v", pkgs)
	}
}

func TestGleamManifest_Parse_KeepsDifferentVersions(t *testing.T) {
	pkgs, _ := parseGleam(t, `packages = [
  { name = "pkg", version = "1.0.0", source = "hex", outer_checksum = "a" },
  { name = "pkg", version = "2.0.0", source = "hex", outer_checksum = "b" },
]
`)
	if len(pkgs) != 2 {
		t.Errorf("expected both versions, got: %+v", pkgs)
	}
}

func TestGleamManifest_Parse_HashOptional(t *testing.T) {
	// Older gleam manifests might not have outer_checksum set.
	// The package should still be emitted.
	pkgs, _ := parseGleam(t, `packages = [
  { name = "pkg", version = "1.0.0", source = "hex" },
]
`)
	if len(pkgs) != 1 || pkgs[0].Hash != "" {
		t.Errorf("expected pkg with empty hash, got: %+v", pkgs)
	}
}

func TestGleamManifest_Parse_MissingFileErrors(t *testing.T) {
	_, err := (hexpm.GleamManifest{}).Parse(fstest.MapFS{}, "manifest.toml")
	if err == nil {
		t.Error("expected error when file missing")
	}
}

func TestGleamManifest_Parse_MalformedTOMLErrors(t *testing.T) {
	fsys := fstest.MapFS{
		"manifest.toml": &fstest.MapFile{Data: []byte("packages = [{ broken")},
	}
	_, err := (hexpm.GleamManifest{}).Parse(fsys, "manifest.toml")
	if err == nil {
		t.Error("expected error on malformed TOML")
	}
}

func TestGleamManifest_Parse_EmptyPackagesList(t *testing.T) {
	pkgs, _ := parseGleam(t, `packages = []
`)
	if len(pkgs) != 0 {
		t.Errorf("expected no packages, got: %+v", pkgs)
	}
}
